Remove unused libxml headers. (#3490)
Fixes fa76d529 ("Remove obsolete libxml dependency").

This fixes building on NixOS with failures like `../src/nemo-main.c:42:10: fatal error: libxml/parser.h: No such file or directory`.